# This is a basic workflow to help you get started with Actions

name: google screenshot

# Controls when the workflow will run
on:
  # # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  WEB_URL: ${{ vars.WEB_URL }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo $WEB_URL 
          pip install selenium
          python googleScreen.py
          echo -- git config user.email
          git config --global user.email "skirep@gmail.com"
          echo -- git config user.name
          git config --global user.name "Oriol C."
          echo -- git config editor
          git config --global core.editor "vim"
          echo -- git clone
          git clone https://$GH_TOKEN@github.com/skirep/actionResult.git
          cd actionResult
          cp ../*.png ./
          echo -- Files inside new repo
          ls
          echo git add -A
          git add -A
          echo git commit
          git commit
          echo git push
          git push
          echo fi !
